<div id="getting-started"></div>
<script type="text/javascript">
    require([
        'jquery',
        'countdown'
    ], function(
        $, countdown
    ) {
        jQuery("#getting-started")
            .countdown("<?php $block->getSpecialDate() ?>", function(event) {
                jQuery(this).text(
                    event.strftime('%D Days %H:%M:%S')
                );
            });
    });
</script>

<?php echo $block->getSpecialDate();

